### ISSUE TITLE
Change composer-plugin-api dependency

### ISSUE THREAD

**Issue by cs278** [eloquent/composer-npm-bridge#10]
Composer is now issuing a warning when using this plugin.

> The "eloquent/composer-npm-bridge" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

https://github.com/composer/composer/commit/ddd140fd1cceece4841e2f0182d0c5e4fed5c10e

**Comment by ezzatron** [comment]
Thanks for the heads up. Unfortunately this repo hasn't been working for some time due to upstream Composer changes. See https://github.com/eloquent/composer-npm-bridge#currently-broken

**Comment by ezzatron** [comment]
Fixed in [3.0.0](https://github.com/eloquent/composer-npm-bridge/releases/tag/3.0.0).
