### ISSUE TITLE
PHP Fatal error:  Class 'Icecave\Isolator\Isolator' not found in eloquent/composer-npm-bridge/src/NpmClient.php on line 35

### ISSUE THREAD

**Issue by nwoetzel** [eloquent/composer-npm-bridge#11]
I am trying to use the bridge in my Symfony2-project (2.7.8).
When I add `"eloquent/composer-npm-bridge":"~3.0"` to my require section an call `composer.phar update`, I get the following error:
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing eloquent/composer-npm-bridge (3.0.0)
    Loading from cache

PHP Fatal error:  Class 'Icecave\Isolator\Isolator' not found in vendor/eloquent/composer-npm-bridge/src/NpmClient.php on line 35
PHP Stack trace:
PHP   1. {main}() /home/vagrant/composer.phar:0
PHP   2. require() /home/vagrant/composer.phar:25
PHP   3. Composer\Console\Application->run() phar:///home/vagrant/composer.phar/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:99
PHP   5. Composer\Console\Application->doRun() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:123
PHP   6. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:166
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:192
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:844
PHP   9. Composer\Command\UpdateCommand->execute() phar:///home/vagrant/composer.phar/vendor/symfony/console/Command/Command.php:259
PHP  10. Composer\Installer->run() phar:///home/vagrant/composer.phar/src/Composer/Command/UpdateCommand.php:158
PHP  11. Composer\Installer->doInstall() phar:///home/vagrant/composer.phar/src/Composer/Installer.php:217
PHP  12. Composer\Installer\InstallationManager->execute() phar:///home/vagrant/composer.phar/src/Composer/Installer.php:585
PHP  13. Composer\Installer\InstallationManager->install() phar:///home/vagrant/composer.phar/src/Composer/Installer/InstallationManager.php:139
PHP  14. Composer\Installer\PluginInstaller->install() phar:///home/vagrant/composer.phar/src/Composer/Installer/InstallationManager.php:152
PHP  15. Composer\Plugin\PluginManager->registerPackage() phar:///home/vagrant/composer.phar/src/Composer/Installer/PluginInstaller.php:62
PHP  16. Eloquent\Composer\NpmBridge\NpmBridgePlugin->__construct() phar:///home/vagrant/composer.phar/src/Composer/Plugin/PluginManager.php:183
PHP  17. Eloquent\Composer\NpmBridge\NpmBridgeFactory::create() vendor/eloquent/composer-npm-bridge/src/NpmBridgePlugin.php:35
PHP  18. Eloquent\Composer\NpmBridge\NpmClient::create() vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php:30

Fatal error: Class 'Icecave\Isolator\Isolator' not found in vendor/eloquent/composer-npm-bridge/src/NpmClient.php on line 35

It works with `"eloquent/composer-npm-bridge":"~2.1"`

**Comment by ezzatron** [comment]
Thanks for the report, I'll look into it.

@jmalloc, this looks related to the issue you were having?

**Comment by nwoetzel** [comment]
Could that be due to changing composer.json
"icecave/isolator": "~2" in version 2.1 to
"icecave/isolator": "^2|^3" in version 3.0.0
but icecave/isolator in version 3 does not have a Class 'Icecave\Isolator\Isolator'  but instead an IsolatorAbstract class? I am not sure what has changed - and if it can just be changed to that, but it is clear, that "icecave/isolator": "^2|^3" is not compatible - only `^2`

**Comment by ezzatron** [comment]
Isolator 3 uses an autoloader to generate `Icecave\Isolator\Isolator` at run time. It seems what was happening is that the autoload mechanism used by Isolator 3 was not available at the time the plugin ran. In addition, once the isolator is generated, it is cached on disk, so that's probably how I missed this issue.

In any case, it's probably better that this plugin doesn't require any dependencies, so I simply re-wrote the portion of the code that used Isolator to function without it.

Can you please try your use-case with `"eloquent/composer-npm-bridge": "dev-develop"`?

**Comment by nwoetzel** [comment]
This is the new error I get with `"eloquent/composer-npm-bridge": "dev-develop"`
[ErrorException]                                                                                      
Argument 2 passed to Eloquent\Composer\NpmBridge\NpmBridge::__construct() must be an instance of Eloquent\Composer\NpmBridge\NpmVendorFinder, null given, called in vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php on line 33 and defined

**Comment by nwoetzel** [comment]
second call to `composer.phar update` works without an error

**Comment by nwoetzel** [comment]
So I had 2.1 installed, changed to `dev-devlop` and called `composer.phar update` and that was the output:
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
The "eloquent/composer-npm-bridge" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing icecave/isolator (2.3.0)
  - Removing eloquent/composer-npm-bridge (2.1.1)
  - Installing eloquent/composer-npm-bridge (dev-develop 41a6a33)
    Cloning 41a6a332c220c752a5b4506d20d5808cebeb17e6

Writing lock file
Generating autoload files

                                                                                                        
  [ErrorException]                                                                                      
  Argument 2 passed to Eloquent\Composer\NpmBridge\NpmBridge::__construct() must be an instance of Eloquent\Composer\NpmBridge\NpmVendorFinder, null given, called in vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php on line 33 and defined

calling `composer.phar update` again works just fine and updates npm dependencies

**Comment by nwoetzel** [comment]
I will try to remove the `"eloquent/composer-npm-bridge": "dev-develop"` - update - and add it back again
I should be able to see if this was just an artifact of the 2.1 installation

**Comment by nwoetzel** [comment]
when I remove and call `composer update` I get this output
~/composer.phar update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing eloquent/composer-npm-bridge (dev-develop)
Writing lock file
Generating autoload files
PHP Fatal error:  Class 'Eloquent\Composer\NpmBridge\NpmBridge' not found in vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php on line 57
PHP Stack trace:
PHP   1. {main}() /home/vagrant/composer.phar:0
PHP   2. require() /home/vagrant/composer.phar:25
PHP   3. Composer\Console\Application->run() phar:///home/vagrant/composer.phar/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:99
PHP   5. Composer\Console\Application->doRun() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:123
PHP   6. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:166
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:192
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:844
PHP   9. Composer\Command\UpdateCommand->execute() phar:///home/vagrant/composer.phar/vendor/symfony/console/Command/Command.php:259
PHP  10. Composer\Installer->run() phar:///home/vagrant/composer.phar/src/Composer/Command/UpdateCommand.php:158
PHP  11. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///home/vagrant/composer.phar/src/Composer/Installer.php:335
PHP  12. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:94
PHP  13. call_user_func:{phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166}() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
PHP  14. Eloquent\Composer\NpmBridge\NpmBridgePlugin->onPostUpdateCmd() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
PHP  15. Eloquent\Composer\NpmBridge\NpmBridgeFactory->createBridge() vendor/eloquent/composer-npm-bridge/src/NpmBridgePlugin.php:89

Fatal error: Class 'Eloquent\Composer\NpmBridge\NpmBridge' not found in vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php on line 57

Call Stack:
    0.0168     418872   1. {main}() /home/vagrant/composer.phar:0
    0.0185     420560   2. require('phar:///home/vagrant/composer.phar/bin/composer') /home/vagrant/composer.phar:25
    0.1375    4004448   3. Composer\Console\Application->run() phar:///home/vagrant/composer.phar/bin/composer:43
    0.1481    4406784   4. Symfony\Component\Console\Application->run() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:99
    0.1515    4544016   5. Composer\Console\Application->doRun() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:123
    0.1605    4683880   6. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:166
    0.1608    4684376   7. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:192
    0.1610    4684952   8. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:844
    0.1635    4690144   9. Composer\Command\UpdateCommand->execute() phar:///home/vagrant/composer.phar/vendor/symfony/console/Command/Command.php:259
    1.8130   11457952  10. Composer\Installer->run() phar:///home/vagrant/composer.phar/src/Composer/Command/UpdateCommand.php:158
  408.2644  240550184  11. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///home/vagrant/composer.phar/src/Composer/Installer.php:335
  408.2649  240550632  12. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:94
  408.3258  240721616  13. call_user_func:~/composer.phar update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing eloquent/composer-npm-bridge (dev-develop)
Writing lock file
Generating autoload files
PHP Fatal error:  Class 'Eloquent\Composer\NpmBridge\NpmBridge' not found in vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php on line 57
PHP Stack trace:
PHP   1. {main}() /home/vagrant/composer.phar:0
PHP   2. require() /home/vagrant/composer.phar:25
PHP   3. Composer\Console\Application->run() phar:///home/vagrant/composer.phar/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:99
PHP   5. Composer\Console\Application->doRun() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:123
PHP   6. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:166
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:192
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:844
PHP   9. Composer\Command\UpdateCommand->execute() phar:///home/vagrant/composer.phar/vendor/symfony/console/Command/Command.php:259
PHP  10. Composer\Installer->run() phar:///home/vagrant/composer.phar/src/Composer/Command/UpdateCommand.php:158
PHP  11. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///home/vagrant/composer.phar/src/Composer/Installer.php:335
PHP  12. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:94
PHP  13. call_user_func:{phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166}() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
PHP  14. Eloquent\Composer\NpmBridge\NpmBridgePlugin->onPostUpdateCmd() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
PHP  15. Eloquent\Composer\NpmBridge\NpmBridgeFactory->createBridge() vendor/eloquent/composer-npm-bridge/src/NpmBridgePlugin.php:89

Fatal error: Class 'Eloquent\Composer\NpmBridge\NpmBridge' not found in vendor/eloquent/composer-npm-bridge/src/NpmBridgeFactory.php on line 57

Call Stack:
    0.0168     418872   1. {main}() /home/vagrant/composer.phar:0
    0.0185     420560   2. require('phar:///home/vagrant/composer.phar/bin/composer') /home/vagrant/composer.phar:25
    0.1375    4004448   3. Composer\Console\Application->run() phar:///home/vagrant/composer.phar/bin/composer:43
    0.1481    4406784   4. Symfony\Component\Console\Application->run() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:99
    0.1515    4544016   5. Composer\Console\Application->doRun() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:123
    0.1605    4683880   6. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/composer.phar/src/Composer/Console/Application.php:166
    0.1608    4684376   7. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:192
    0.1610    4684952   8. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/composer.phar/vendor/symfony/console/Application.php:844
    0.1635    4690144   9. Composer\Command\UpdateCommand->execute() phar:///home/vagrant/composer.phar/vendor/symfony/console/Command/Command.php:259
    1.8130   11457952  10. Composer\Installer->run() phar:///home/vagrant/composer.phar/src/Composer/Command/UpdateCommand.php:158
  408.2644  240550184  11. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///home/vagrant/composer.phar/src/Composer/Installer.php:335
  408.2649  240550632  12. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:94
  408.3258  240721616  13. call_user_func:{phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166}() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
  408.3258  240721744  14. Eloquent\Composer\NpmBridge\NpmBridgePlugin->onPostUpdateCmd() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
  408.3258  240721832  15. Eloquent\Composer\NpmBridge\NpmBridgeFactory->createBridge() vendor/eloquent/composer-npm-bridge/src/NpmBridgePlugin.php:89{phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166}() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
  408.3258  240721744  14. Eloquent\Composer\NpmBridge\NpmBridgePlugin->onPostUpdateCmd() phar:///home/vagrant/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:166
  408.3258  240721832  15. Eloquent\Composer\NpmBridge\NpmBridgeFactory->createBridge() vendor/eloquent/composer-npm-bridge/src/NpmBridgePlugin.php:89


This might be realted to #5 and could be the same error as observed there

**Comment by nwoetzel** [comment]
When adding `"eloquent/composer-npm-bridge": "dev-develop"` back in it works as expected:
~/composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing eloquent/composer-npm-bridge (dev-develop 41a6a33)
    Cloning 41a6a332c220c752a5b4506d20d5808cebeb17e6

Writing lock file
Generating autoload files
Updating NPM dependencies for root project
npm http GET https://registry.npmjs.org/jquery
...

Thanks a lot for the quick fix. Looking forward to the actual release!

**Comment by ezzatron** [comment]
Yeah, from memory, Composer does some weird thing where it tries to run the old version of a plugin, even when updating the plugin itself. This explains the "works on second run" you're seeing. I'm not aware of any way to "fix" the issue. From a quick search, this looks to be related: [composer/issues#4520](https://github.com/composer/composer/issues/4520).

So long as it works when you do something like the following:

- delete `vendor` (and `composer.lock` for good measure)
- update `composer-npm-bridge` dependency
- `composer update`

Then I consider it to be "working".

I'll probably add something to the readme about this at some point.

**Comment by ezzatron** [comment]
Fixed in [3.0.1](https://github.com/eloquent/composer-npm-bridge/releases/tag/3.0.1).

**Comment by nwoetzel** [comment]
I can confirm that it works with 3.0.1. after deleting vendor, composer.lock, node_modules (for my project of course...)
Thanks a lot for the quick help and fix!

**Comment by ezzatron** [comment]
No worries, thanks for the report!
