### ISSUE TITLE
ProcesssTimedOutException for lengthy installations

### ISSUE THREAD

**Issue by uuf6429** [eloquent/composer-npm-bridge#13]
NPM might reach process timeout:
> [Symfony\Component\Process\Exception\ProcessTimedOutException]
>  The process ""C:\Program Files\nodejs\\npm.CMD" "install"" exceeded the timeout of 300 seconds.

Probably the timeout should be removed (significantly increased).

**Comment by uuf6429** [comment]
Sure, I'll try to give a try soon. Too bad I lost the original stack trace :D

**Comment by ezzatron** [comment]
Released in [4.1.0](https://github.com/eloquent/composer-npm-bridge/releases/4.1.0)
