### ISSUE TITLE
npm update creates package-lock.json, composer update with bridge deleted package-lock.json and creates npm-shrinkwrap.json instead

### ISSUE THREAD

**Issue by BrianGilbert** [eloquent/composer-npm-bridge#15]
Is there a way to configure conposer-npm-bridge to use the newer package.lock.json rather than deleting this and creating a npm-shrinkwrap.json file?

**Comment by ezzatron** [comment]
That's definitely a good idea. There is no way to do that currently, but I would welcome a PR if you're interested in making it happen!

**Comment by BrianGilbert** [comment]
@ezzatron Is there currently any way to inspect what version of NPM is installed via the existing code of this package?

**Comment by ezzatron** [comment]
I would probably favour removing it, and just targeting the latest NPM version. The new lock files are much more closely aligned with how Composer's lock files work anyway.

**Comment by BrianGilbert** [comment]
PR submitted: https://github.com/eloquent/composer-npm-bridge/pull/16

**Comment by ezzatron** [comment]
Fixed in [4.0.0](https://github.com/eloquent/composer-npm-bridge/releases/4.0.0).
