### ISSUE TITLE
Compatibility with Composer 2.x

### ISSUE THREAD

**Issue by oliver-graetz** [eloquent/composer-npm-bridge#22]
This is displayed when running Composer on a project using this plugin:

```
The "eloquent/composer-npm-bridge" plugin was skipped because it requires a Plugin API version ("^1")
that does not match your Composer installation ("2.0.0"). You may need to run composer update with
the "--no-plugins" option.
Composer version 2.0.3 2020-10-28 15:50:55
```

Since Composer will not retain compatibility with the 1.x version for very long, an update for this plugin is badly needed.

**Comment by ezzatron** [comment]
Thanks. I'm aware that Composer 2 was released recently, unfortunately I have a fairly limited amount of time to devote to open source at the moment. I'll do my best to get to this soon, but a PR is probably the best way to speed things along if you're able to help out 👍

**Comment by TreeNode** [comment]
Looks like very minimal changes needed. However, I don't see anything in the code for ->addInstaller(...) so I don't know how to update that.

https://github.com/composer/installers/commit/d2a98321ab66945396ef147387f93eee4c05089f#

**Comment by ezzatron** [comment]
Added in [5.0.0](https://github.com/eloquent/composer-npm-bridge/releases/tag/5.0.0)
